[package]
name = "example-websocket-chat"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["websocket"]}
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.17"
tracing-subscriber = "0.2.24"
