[package]
name = "example-tls"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../", features = ["tls"]}
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
