[package]
name = "example-combined-listeners"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../" }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
