[package]
name = "poem"
version = "0.8.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "Poem is a full-featured and easy-to-use web framework with the Rust programming language."
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/poem/"
homepage = "https://github.com/poem-web/poem"
repository = "https://github.com/poem-web/poem"
keywords = ["http", "web", "framework", "async"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket",
]

[features]
default = []
websocket = ["tokio-tungstenite"]
multipart = ["multer"]
tls = ["tokio-rustls"]
sse = []
compression = ["async-compression", "typed-headers"]
tower-compat = ["tower"]

[dependencies]
poem-derive = { path = "../poem-derive", version = "0.8.0" }

async-trait = "0.1.51"
bytes = "1.1.0"
futures-util = { version = "0.3.17", features = ["sink"] }
http = "0.2.5"
hyper = { version = "0.14.13", features = ["http1", "http2", "server", "runtime", "stream"] }
mime = "0.3.16"
tokio = { version = "1.12.0", features = ["sync", "rt", "net", "fs", "time", "macros", "signal"] }
tokio-util = { version = "0.6.8", features = ["io"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_urlencoded = "0.7.0"
sha1 = "0.6.0"
base64 = "0.13.0"
tokio-stream = "0.1.7"
cookie = { version = "0.15.1", features = ["percent-encode"] }
parking_lot = "0.11.2"
askama = "0.10.5"
thiserror = "1.0.29"
anyhow = "1.0.44"
pin-project-lite = "0.2.7"
percent-encoding = "2.1.0"
once_cell = "1.8.0"
regex = "1.5.4"
mime_guess = "2.0.3"
smallvec = "1.6.1"
nom = "7.0.0"
tracing = "0.1.28"

# Non-feature optional dependencies
multer = { version = "2.0.1", features = ["tokio"], optional = true }
tokio-tungstenite = { version = "0.15.0", optional = true }
tokio-rustls = { version = "0.22.0", optional = true }
async-compression = { version = "0.3.8", optional = true, features = ["tokio", "gzip", "brotli", "deflate"] }
tower = { version = "0.4.8", optional = true, default-features = true, features = ["util", "buffer"] }

# Feature optional dependencies
typed-headers = { version = "0.2.0", optional = true }
tempfile = { version = "3.2.0", optional = true }

[dev-dependencies]
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
webpki = "0.21.4"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
